#!/bin/bash
# Creates agent-specific tasks for an epic
# Usage: ./create-tasks.sh <epic_id> <feature_name>

EPIC_ID="$1"
FEATURE_NAME="$2"

if [ -z "$EPIC_ID" ] || [ -z "$FEATURE_NAME" ]; then
  echo "Usage: $0 <epic_id> <feature_name>"
  echo ""
  echo "Example:"
  echo "  $0 ABC-123 \"Create Todo with Priority\""
  exit 1
fi

echo "📝 Creating agent tasks for epic: $EPIC_ID"
echo "Feature: $FEATURE_NAME"
echo ""
echo "The following tasks should be created in Linear:"
echo "============================================"
echo ""
echo "PHASE 1 (Sequential):"
echo "---------------------"
echo "Title: [Test-First] Write tests for $FEATURE_NAME"
echo "Parent: $EPIC_ID"
echo "Labels: agent:test-first, phase:1-red"
echo "State: Ready"
echo "Description: Write BDD scenarios and unit tests that fail initially (RED state)"
echo ""
echo "PHASE 2 (Parallel, blocked by Phase 1):"
echo "----------------------------------------"
echo "Task 1:"
echo "Title: [Domain] Implement entity and service for $FEATURE_NAME"
echo "Parent: $EPIC_ID"
echo "Labels: agent:domain-logic, phase:2-green"
echo "Blocked by: Phase 1 issue"
echo "Description: Implement domain entities, services, and port interfaces"
echo ""
echo "Task 2:"
echo "Title: [Database] Create schema and repository for $FEATURE_NAME"
echo "Parent: $EPIC_ID"
echo "Labels: agent:database, phase:2-green"
echo "Blocked by: Phase 1 issue"
echo "Description: Create migrations, RLS policies, and repository implementation"
echo ""
echo "PHASE 3 (Parallel, blocked by Phase 2):"
echo "----------------------------------------"
echo "Task 1:"
echo "Title: [Adapter] Implement REST API and bot handlers for $FEATURE_NAME"
echo "Parent: $EPIC_ID"
echo "Labels: agent:adapter, phase:3-adapters"
echo "Blocked by: Phase 2 issues"
echo "Description: Implement Echo REST API endpoints and Telegram bot handlers"
echo ""
echo "Task 2:"
echo "Title: [AI/NLP] Implement intent parsing for $FEATURE_NAME"
echo "Parent: $EPIC_ID"
echo "Labels: agent:ai-nlp, phase:3-adapters"
echo "Blocked by: Phase 2 issues"
echo "Description: Implement Perplexity intent parsing and NLP features"
echo ""
echo "PHASE 4 (Sequential, blocked by Phase 3):"
echo "------------------------------------------"
echo "Title: [Infrastructure] Deploy $FEATURE_NAME"
echo "Parent: $EPIC_ID"
echo "Labels: agent:infrastructure, phase:4-deploy"
echo "Blocked by: Phase 3 issues"
echo "Description: Update CI/CD, deploy to Railway, verify health checks"
echo ""
echo "============================================"
echo ""
echo "Copy these task descriptions and create them in Linear."
echo "Then use the orchestrator droid to coordinate execution."
